### ISSUE TITLE
SampleApplication.onCreate 不调用

### ISSUE THREAD

**Issue by walfud** [TinkerPatch/tinkerpatch-easy-sample#1]
1. clone tinkerpatch-easy-sample
2. 修改 `SampleApplication`, 重载 `onCreate` 函数, 并 `Log.e("Tinker", "Called at SampleApplication.onCreate")`
观察效果, 并没有打印出该日志. 下断点也不走.

对比实验:
1. clone tinkerpatch-sample.  <strong>注意, 这里不是 easy, 而是另一个需要 ApplicationLike 的 sample</strong>
2. 同上的修改
正常调用了 SampleApplicationLike 的 onCreate.

**Comment by shwenzhang** [comment]
1.0.1版本已经fixed
