### ISSUE TITLE
1.1.3版本的合成补丁错误率明显上升

### ISSUE THREAD

**Issue by 601367322** [TinkerPatch/tinkerpatch-easy-sample#10]
1.1.1的sdk：

出现次数	最后出现时间	错误码
3	2017-02-19 17:06:03	-2
2	2017-02-19 22:06:16	-3

1.1.3的sdk：

出现次数	最后出现时间	错误码
78	2017-02-20 10:14:16	-2
3	2017-02-20 09:22:45	-3

**Comment by simpleton** [comment]
多谢反馈，我blame一下，稍后给你回复。如果你收集到更多错误log，也欢迎贴在这里。

**Comment by simpleton** [comment]
@601367322 sorry for missing feedback. 我们的最新版为1.1.4（支持加固的1.1.5将于下周发布），欢迎试用。
