### ISSUE TITLE
下载这个sample 跑的时候总是报错，appkey 我用自己申请的；

### ISSUE THREAD

**Issue by zhuangzeqin** [TinkerPatch/tinkerpatch-easy-sample#12]
Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com
07-31 10:46:28.236 28437-28437/com.tinkerpatch.easy_sample W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
07-31 10:46:28.244 28437-28437/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469188244, method:GET, body:null
07-31 10:46:28.360 28437-28489/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
07-31 10:46:28.361 28437-28489/com.tinkerpatch.easy_sample W/Tinker.PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469188244
07-31 10:46:28.361 28437-28489/com.tinkerpatch.easy_sample E/Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com
07-31 10:46:28.457 28437-28437/com.tinkerpatch.easy_sample W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
07-31 10:46:28.467 28437-28437/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469188466, method:GET, body:null
07-31 10:46:28.591 28437-28489/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
07-31 10:46:28.591 28437-28489/com.tinkerpatch.easy_sample W/Tinker.PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469188466
07-31 10:46:28.591 28437-28489/com.tinkerpatch.easy_sample E/Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com
07-31 10:46:28.644 28437-28437/com.tinkerpatch.easy_sample W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
07-31 10:46:28.652 28437-28437/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469188651, method:GET, body:null
07-31 10:46:28.756 28437-28489/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
07-31 10:46:28.757 28437-28489/com.tinkerpatch.easy_sample W/Tinker.PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469188651
07-31 10:46:28.757 28437-28489/com.tinkerpatch.easy_sample E/Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com
07-31 10:46:29.043 28437-28437/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/c/691813ccdf20e099?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469189042, method:GET, body:null
07-31 10:46:29.228 28437-28489/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
07-31 10:46:29.229 28437-28489/com.tinkerpatch.easy_sample W/Tinker.MainActivity: request config failed, exception:java.io.FileNotFoundException: http://q.tinkerpatch.com/c/691813ccdf20e099?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469189042
07-31 10:46:29.755 28437-28437/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/c/691813ccdf20e099?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469189755, method:GET, body:null
07-31 10:46:29.920 28437-28489/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
07-31 10:46:29.921 28437-28489/com.tinkerpatch.easy_sample W/Tinker.MainActivity: request config failed, exception:java.io.FileNotFoundException: http://q.tinkerpatch.com/c/691813ccdf20e099?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469189755
07-31 10:46:58.522 28437-28437/com.tinkerpatch.easy_sample W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
07-31 10:46:58.531 28437-28437/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469218531, method:GET, body:null
07-31 10:46:58.671 28437-28489/com.tinkerpatch.easy_sample I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
07-31 10:46:58.672 28437-28489/com.tinkerpatch.easy_sample W/Tinker.PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-5c182370f60b&v=1501469218531
07-31 10:46:58.672 28437-28489/com.tinkerpatch.easy_sample E/Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com

**Comment by simpleton** [comment]
也需要在后台建立想对应的appVersion，并上传相应的patch

**Comment by zhuangzeqin** [comment]
这个肯定有； 自己在后台填写了app的版本；生产相应的差异包上传上去； 但是APP 重新启动的时候；没有任何的效果；我用本地合成差异包之后；我用Tinker 的方法更新差异包确实可以的；TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(), Environment.getExternalStorageDirectory().getAbsolutePath() + "/patch_signed_7zip.apk"); 这是我用本地自己合成确实可以的；也就是说第三方托管的补丁包  我用的是TinkerPatch.with().fetchPatchUpdate(true);每次强制访问服务器更新，但是实际上没有任何的效果，我用的是官方提供的Demo 跑的

**Comment by simpleton** [comment]
java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/
691813ccdf20e099/3.0.1?d=091c5ed9-f62a-4274-a50a-
5c182370f60b&v=1501469188244

从url看，3.0.1是我sample里默认的appVersion。请确认你的后台也建立了这个appVersion

2017-07-31 13:42 GMT+08:00 zhuangzeqin <notifications@github.com>:

**Comment by zhuangzeqin** [comment]
抱歉；是自己的 appVersion 搞错了；我重新弄好之后就可以了； 谢谢你提供的帮助

**Comment by simpleton** [comment]
没关系，这里我close了
