### ISSUE TITLE
code:-2 合成补丁时异常 如何排查问题

### ISSUE THREAD

**Issue by look0089** [TinkerPatch/tinkerpatch-easy-sample#13]
自己参照文档写了个 demo
环境：
compile("com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.1.8")
classpath "com.tinkerpatch.sdk:tinkerpatch-gradle-plugin:1.1.8"

手机：红米note4x

执行

`    String path = Environment.getExternalStorageDirectory().getAbsolutePath()+"/patch_signed_7zip.apk";    
            TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(), path);    
`

报错

`Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2
`

code:-2 的产生有哪些可能？

**Comment by shwenzhang** [comment]
对于tinkerpatch版本，是需要将补丁上传到我们服务器测试的，而不是sdcard
