### ISSUE TITLE
git clone 后，用as3.0 打开报下面的错误

### ISSUE THREAD

**Issue by ibmsoft** [TinkerPatch/tinkerpatch-easy-sample#14]
1、先是报找不到 1.1.9
Error:Could not find com.tinkerpatch.sdk:tinkerpatch-gradle-plugin:1.1.9.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.jar
    file:/Users/apple/.m2/repository/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.pom
    file:/Users/apple/.m2/repository/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.jar
    https://jcenter.bintray.com/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.pom
    https://jcenter.bintray.com/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.jar
    https://dl.google.com/dl/android/maven2/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.pom
    https://dl.google.com/dl/android/maven2/com/tinkerpatch/sdk/tinkerpatch-gradle-plugin/1.1.9/tinkerpatch-gradle-plugin-1.1.9.jar
Required by:
    project :

2、修改成 1.1.8 后
Error:Could not set unknown property 'supportComponent' for  tinkerEnable = true
 reflectApplication = true
 protectedApp = false
 appKey = 
 autoBackupApkPath = 
 backupFileNameFormat = ${appName}-${variantName}
         of type com.tinkerpatch.sdk.build.gradle.extension.TinkerPatchSupportExtension.

**Comment by ibmsoft** [comment]
1.1.8
注释掉
//    supportComponent = false
就可以了

**Comment by simpleton** [comment]
对，那个是新版的参数
