### ISSUE TITLE
Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/R$id;}

### ISSUE THREAD

**Issue by jasonlee3652** [TinkerPatch/tinkerpatch-easy-sample#15]
我准备了个基准包，然后基于这个基准包的代码再app的gradle中添加了一行implementation 'com.android.support.constraint:constraint-layout:1.0.2'。然后执行tinkerPatchReplease生成补丁，结果报错了：

错误日志：
Warning:ignoreWarning is false, but we found some loader class has been changed in new dex. Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/R$id;}

Error:com.tencent.tinker.build.util.TinkerPatchException: some loader class has been changed in new dex. Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/R$id;}

其他配置都是正确的，不在app的gradle中添加implementation 'com.android.support.constraint:constraint-layout:1.0.2'是可以生成补丁的。这个是什么原因呢

**Comment by shwenzhang** [comment]
这个类变化了，在这个case下面，可以直接把ignorewarning改为true
