### ISSUE TITLE
对于appVersion的理解

### ISSUE THREAD

**Issue by Luopan1** [TinkerPatch/tinkerpatch-easy-sample#21]
tinkerpatchSupport中的appVersion的理解有点问题，这里我先说一下我自己的理解，请教一下是否是这样的，
<hr/>
比如说现在我创建了一个app,自身的版本号为1.0.0，并且也集成了tinker，tinkerpatchSupport中的appVersion也是1.0.0，当应用发布出去之后，发现了bug,我要热更新修复bug,使用的是TinkerPlatform进行下发管理，再进行打补丁的时候，tinkerpatchSupport中的appVersion就要升级到1.0.1，TinkerPlatform中只需要在App版本为1.0.0的上面上传补丁包就行了。

用户手机上的app版本是多少，就在TinkerPlatform上创建多少版本号的应用，当哪个版本发生问题，就在相应的应用上增加tinkerpatchSupport中的appVersion版本号就行。

请问这样理解对吗 ？谢谢

**Comment by simpleton** [comment]
你对appVersion的理解是正确的，我们这里推荐和app本身的appVersion保持一致，这样可以保证每次去应用商店更新的时候，这个appVersion是会被更新的。 再进行打补丁的时候，appVersion是不会进行更新的，我们内部会维护一个patchVersion，每次都是使用最新的patch进行更新

但其实这个tinkerpatchSupport中的appVersion完全是tinker在使用，只是为了标识一个APK的独立版本，与APP的appVersion并无强关联。
