### ISSUE TITLE
cleanPatch() 无效

### ISSUE THREAD

**Issue by longtaoge** [TinkerPatch/tinkerpatch-easy-sample#3]
patch 加载成功后      调用 TinkerPatch.with().cleanPatch();  预期为可重新加载patch ,实际无法重新加载

**Comment by shwenzhang** [comment]
肯定不行啊，因为版本信息还存在，不能再加载已经加载过的版本。除非你把tinker_server的目录也删掉。因为设计上就是不允许自己去删除的
