### ISSUE TITLE
通过 autoBackupApkPath 保存编译的产物 apk/mapping.txt/R.txt 文件出现问题

### ISSUE THREAD

**Issue by yinyiliang** [TinkerPatch/tinkerpatch-easy-sample#5]
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=1.0 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
Task 'autoBackupApkPath' not found in root project 'BookReader-master'.

**Comment by simpleton** [comment]
@yinyiliang 麻烦问下你试用的版本号，这个参数是1.0.x新加入的

**Comment by yinyiliang** [comment]
我使用的是1.0.1版本

**Comment by yinyiliang** [comment]
@simpleton 我使用的是1.0.1版本

**Comment by simpleton** [comment]
@yinyiliang 抱歉，回复晚了。从log的错误看是因为没有r.txt这个文件了，在生成patch的时候，tinker是需要r.txt和proguardMapping的。
