### ISSUE TITLE
Error:Could not find com.tencent.tinker:tinker-patch-gradle-plugin:1.7.7

### ISSUE THREAD

**Issue by 601367322** [TinkerPatch/tinkerpatch-easy-sample#6]
Error:Could not find com.tencent.tinker:tinker-patch-gradle-plugin:1.7.7.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.jar
    file:/Users/bingbing/.m2/repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.pom
    file:/Users/bingbing/.m2/repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.jar
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.pom
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.jar
Required by:
    :tinkerpatch-easy-sample:unspecified > com.tinkerpatch.sdk:tinkerpatch-gradle-plugin:1.0.3

**Comment by simpleton** [comment]
你使用了1.0.4么？

**Comment by simpleton** [comment]
@601367322 不好意思，由于tinker1.7.7还未发布，我基于1.7.7开发了一些功能使用了localmaven，所以你会拉不到这个repo。 我现在相关文档已经revert了，你可以使用1.0.2的版本，这个是基于tinker 1.7.6开发的。十分抱歉。
