### ISSUE TITLE
如何开发环境关闭tinker

### ISSUE THREAD

**Issue by small-tree** [TinkerPatch/tinkerpatch-easy-sample#7]
如何在开发环境关闭tinker，不然每次运行都在build/bakapk 生成文件

**Comment by summerzh** [comment]
我也想在开发时关闭掉tinker，否则不能使用intant run，编译速度很慢。但我发现tinkerEnable = false还是关闭不掉，但是我测试过tinker的官方demo是可以关闭掉的。不知道是不是tinkerpatch的bug，同求关闭tinker的方法？

**Comment by shwenzhang** [comment]
今天会发版本fix

**Comment by small-tree** [comment]
tinkerenable = false
这是我遇到的问题
Error:A problem occurred configuring project ':minxindai40'.
> can't find tinkerProcessDebugManifest, you must init tinker plugin first!
也会修复么

**Comment by simpleton** [comment]
@small-tree 是的，这个现在已经在master分支修复了，只不过是基于tinker 1.7.7内核开发的，需要等待tinker1.7.7的发布。

**Comment by small-tree** [comment]
好的 厉害

**Comment by simpleton** [comment]
@small-tree @summerzh 不能关闭tinker的问题已经在1.1.0版本修复了。
